name = "publisher-dashboard"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "publisher-dashboard-db"
database_id = "f9bae933-c694-4c43-a425-4dd6bde62c62"
migrations_dir = "migrations"
